# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3acd731aa23db49efb7cba356faa29fa50f3a246ad9f56e6069f539be9170cf7350152b4d49bf3e6311cdb173952517bb1b2e352dc79055b5d7d143a6b5cfcd8

test:
  secret_key_base: 45c4f2cbf496615ae41be2df8ca5f3848c9b2cb5c5387f1fa6b6e8a4eca1db8cb4a14cf76bee5103dfee19731cc502d13c3e0caa736e9d69187196e1e93646a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
